spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mini_post_db
    username: root
    password: 3173

mybatis:
  mapper-locations:
    - /mappers/*.xml
